print("master created.....")

print("master CODING.....")
print("master CODING.....")
print("master CODING.....")
print("master CODING.....")

print("master 2nd CODING.....")
print("master 2nd CODING.....")
print("master 2nd CODING.....")
print("master 2nd CODING.....")
print("master 2nd CODING.....")
print("master 2nd CODING.....")

print("master 3d CODING.....")
print("master 3d CODING.....")
print("master 3d CODING.....")
print("master 3d CODING.....")
print("master 3d CODING.....")
print("master 3d CODING.....")
print("master 3d CODING.....")
print("master 3d CODING.....")

print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")
print("master 4th CODING.....")

